image: python:3.10

stages:
  - test

before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install pytest-cov  

test:
  stage: test
  tags:
    - docker
  script:
    - pytest --cov=. --cov-report=xml --cov-report=term
  coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+)%/'
  artifacts:
    paths:
      - coverage.xml
    when: always
