image: python:3.10

stages:
  - test
  - build

before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install pytest-cov  

test:
  stage: test
  tags:
    - docker
  script:
    - pytest --cov=. --cov-report=xml --cov-report=term
  coverage: '/TOTAL.*\s+(\d+%)$/'
  artifacts:
    paths:
      - dist/
    when: always

build_develop:
  stage: build
  tags:
    - docker
  only:
    - develop
  script:
    - echo "Building for develop branch..."
    - hatch build
    - ls dist/
  after_script:
    - git config --global user.email "ci@cd.com"
    - git config --global user.name "CI/CD"
    - |
      TAG_NAME="develop-$(date +'%Y%m%d%H%M%S')"
      git tag $TAG_NAME
      git push origin $TAG_NAME