image: python:3.10

stages:
  - test
  - build

before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install pytest-cov  

test:
  stage: test
  tags:
    - docker
  script:
    - pytest --cov=. --cov-report=xml --cov-report=term
  coverage: '/TOTAL.*\s+(\d+%)$/'
  artifacts:
    paths:
      - dist/
    when: always

build_develop:
  stage: build
  tags:
    - docker
  only:
    - tags
  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - echo "my-arithmetic-$USER deployment on develop servers"
    - hatch build
    - ls dist/
  rules:
    - if: $CI_COMMIT_BRANCH == "develop" 

build_main:
  stage: build
  tags:
    - docker
  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - echo "my-arithmetic-$USER deployment on servers"
    - hatch build
    - ls dist/
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
